import torch
import numpy as np
from PIL import Image
import io
import requests
import os

class SaveToPhoneTelegram:
    def __init__(self):
        self.output_dir = "temp"

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "images": ("IMAGE",),
                "bot_token": ("STRING", {"default": "YOUR_BOT_TOKEN_HERE"}),
                "chat_id": ("STRING", {"default": "YOUR_CHAT_ID_HERE"}),
                "caption": ("STRING", {"default": "Generated by ComfyUI"}),
            },
        }

    RETURN_TYPES = ()
    FUNCTION = "send_to_phone"
    OUTPUT_NODE = True
    CATEGORY = "Image/Postprocessing"

    def send_to_phone(self, images, bot_token, chat_id, caption):
        results = []
        
        for image in images:
            # Convert tensor to PIL
            i = 255. * image.cpu().numpy()
            img = Image.fromarray(np.uint8(i))
            
            # Save to byte buffer
            bio = io.BytesIO()
            img.save(bio, format="PNG")
            bio.seek(0)
            
            # Send to Telegram API
            url = f"https://api.telegram.org/bot{bot_token}/sendPhoto"
            files = {'photo': ('image.png', bio, 'image/png')}
            data = {'chat_id': chat_id, 'caption': caption}
            
            try:
                response = requests.post(url, data=data, files=files)
                if response.status_code == 200:
                    print(f"Successfully sent to phone!")
                else:
                    print(f"Failed to send: {response.text}")
            except Exception as e:
                print(f"Error sending to Telegram: {e}")

        return {"ui": {"images": results}}

NODE_CLASS_MAPPINGS = {
    "SaveToPhoneTelegram": SaveToPhoneTelegram
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "SaveToPhoneTelegram": "📲 Save to Phone (Telegram)"
}